export interface Watch {
    id: string;
    name: string;
    brand: string;
    collection: string;
    price: number;
    image: string;
    gender: 'Men' | 'Women' | 'Unisex';
    category: 'Classic' | 'Sports' | 'Smart' | 'Luxury';
    description: string;
    featured?: boolean;
    onSale?: boolean;
    discountPrice?: number;
}

export const WATCH_COLLECTION: Watch[] = [
    // --- ROLEX (Target 4+) ---
    {
        id: 'r1',
        name: 'DAY-DATE 40',
        brand: 'Rolex',
        collection: 'Oyster Perpetual',
        price: 2800000,
        image: '/images/generated/men_watch_gold.png',
        gender: 'Men',
        category: 'Luxury',
        description: 'The president\'s watch, redefined in 18k yellow gold.',
        featured: true
    },
    {
        id: 'r2',
        name: 'SUBMARINER DATE',
        brand: 'Rolex',
        collection: 'Professional',
        price: 950000,
        image: '/images/generated/men_watch_4.png',
        gender: 'Men',
        category: 'Sports',
        description: 'The reference among divers\' watches.',
    },
    {
        id: 'r3',
        name: 'LADY-DATEJUST',
        brand: 'Rolex',
        collection: 'Classic',
        price: 850000,
        image: '/images/generated/women_watch_gold.png',
        gender: 'Women',
        category: 'Luxury',
        description: 'Grace and elegance in a timeless design.',
    },
    {
        id: 'r4',
        name: 'DAYTONA LUXE',
        brand: 'Rolex',
        collection: 'Professional',
        price: 3500000,
        image: '/images/generated/rolex_daytona.png',
        gender: 'Men',
        category: 'Sports',
        description: 'The ultimate tool watch for those with a passion for driving and speed.',
    },

    // --- OMEGA (Target 4+) ---
    {
        id: 'o1',
        name: 'SPEEDMASTER MOON',
        brand: 'Omega',
        collection: 'Speedmaster',
        price: 650000,
        image: '/images/generated/men_watch_sport.png',
        gender: 'Men',
        category: 'Sports',
        description: 'The legendary chronograph that accompanied the Apollo missions.',
    },
    {
        id: 'o2',
        name: 'CONSTELLATION CO-AXIAL',
        brand: 'Omega',
        collection: 'Constellation',
        price: 450000,
        image: '/images/generated/omega_constellation_unique.png',
        gender: 'Women',
        category: 'Luxury',
        description: 'Characterized by its famous "claws" and beautiful mother-of-pearl dial.',
    },
    {
        id: 'o3',
        name: 'SEAMASTER DIVER 300M',
        brand: 'Omega',
        collection: 'Seamaster',
        price: 520000,
        image: '/images/generated/omega_seamaster.png',
        gender: 'Men',
        category: 'Sports',
        description: 'A professional timepiece with a maritime soul.',
    },
    {
        id: 'o4',
        name: 'DE VILLE PRESTIGE',
        brand: 'Omega',
        collection: 'De Ville',
        price: 380000,
        image: '/images/generated/omega_deville.png',
        gender: 'Women',
        category: 'Classic',
        description: 'Simple and elegant, the quintessential dress watch.',
    },

    // --- PATEK PHILIPPE (Target 4+) ---
    {
        id: 'p1',
        name: 'NAUTILUS BLUE',
        brand: 'Patek Philippe',
        collection: 'Nautilus',
        price: 6500000,
        image: '/images/generated/patek_nautilus.png',
        gender: 'Men',
        category: 'Luxury',
        description: 'An elegant sports watch with an iconic porthole design.',
        featured: true
    },
    {
        id: 'p2',
        name: 'ANNUAL CALENDAR',
        brand: 'Patek Philippe',
        collection: 'Complications',
        price: 3200000,
        image: '/images/generated/men_watch_2.png',
        gender: 'Men',
        category: 'Luxury',
        description: 'Mechanical excellence with a sophisticated aesthetic.',
    },
    {
        id: 'p3',
        name: 'CALATRAVA WHITE GOLD',
        brand: 'Patek Philippe',
        collection: 'Calatrava',
        price: 2500000,
        image: '/images/generated/women_watch_silver.png',
        gender: 'Women',
        category: 'Classic',
        description: 'Pure elegance and minimalist design.',
    },
    {
        id: 'p4',
        name: 'AQUANAUT SPORT',
        brand: 'Patek Philippe',
        collection: 'Aquanaut',
        price: 4200000,
        image: '/images/generated/men_watch_3.png', // Placeholder unique-ish
        gender: 'Men',
        category: 'Sports',
        description: 'Modern, sporty and chic.',
    },

    // --- CARTIER (Target 4+) ---
    {
        id: 'c1',
        name: 'BALLON BLEU',
        brand: 'Cartier',
        collection: 'Ballon Bleu',
        price: 1200000,
        image: '/images/generated/women_watch_1.png',
        gender: 'Women',
        category: 'Luxury',
        description: 'Floating like a balloon, as blue as the sapphire cabochon.',
        featured: true
    },
    {
        id: 'c2',
        name: 'SANTOS DE CARTIER',
        brand: 'Cartier',
        collection: 'Santos',
        price: 680000,
        image: '/images/generated/cartier_santos.png',
        gender: 'Men',
        category: 'Luxury',
        description: 'One of the first wristwatches in history, designed for pilots.',
    },
    {
        id: 'c3',
        name: 'PANTHÈRE DE CARTIER',
        brand: 'Cartier',
        collection: 'Panthère',
        price: 2200000,
        image: '/images/generated/cartier_panthere.png',
        gender: 'Women',
        category: 'Luxury',
        description: 'A jewelry watch that doubles as a piece of high art.',
    },
    {
        id: 'c4',
        name: 'TANK LOUIS',
        brand: 'Cartier',
        collection: 'Tank',
        price: 850000,
        image: '/images/generated/women_watch_3.png', // Corrected tag to match image
        gender: 'Women',
        category: 'Classic',
        description: 'The symbol of historical elegance since 1917.',
    },

    // --- AUDEMARS PIGUET (Target 4) ---
    {
        id: 'a1',
        name: 'ROYAL OAK SELFWINDING',
        brand: 'Audemars Piguet',
        collection: 'Royal Oak',
        price: 4500000,
        image: '/images/generated/hero_banner.png',
        gender: 'Men',
        category: 'Luxury',
        description: 'The iconic octagonal bezel and integrated bracelet.',
        featured: true
    },
    {
        id: 'a2',
        name: 'ROYAL OAK ROSE',
        brand: 'Audemars Piguet',
        collection: 'Royal Oak',
        price: 5500000,
        image: '/images/generated/hero_banner_v2.png',
        gender: 'Men',
        category: 'Luxury',
        description: 'Warm gold tones for the ultimate statement.',
    },
    {
        id: 'a3',
        name: 'OFFSHORE CHRONO',
        brand: 'Audemars Piguet',
        collection: 'Royal Oak Offshore',
        price: 3200000,
        image: '/images/generated/men_watch_5.png',
        gender: 'Men',
        category: 'Sports',
        description: 'Robust and powerful chronograph performance.',
    },
    {
        id: 'a4',
        name: 'CONCEPT TOURBILLON',
        brand: 'Audemars Piguet',
        collection: 'Royal Oak Concept',
        price: 9500000,
        image: '/images/generated/men_watch_6.png',
        gender: 'Men',
        category: 'Luxury',
        description: 'The cutting edge of haute horlogerie.',
    },

    // --- INTERNATIONAL BRANDS (Expansion) ---
    {
        id: 'i1',
        name: 'A-LOGO ELITE',
        brand: 'AIGNER',
        collection: 'Heritage',
        price: 85000,
        image: '/images/generated/aigner_watch.png',
        gender: 'Men',
        category: 'Luxury',
        description: 'Distinctive horseshoe design with premium leather.'
    },
    {
        id: 'i2',
        name: 'AX CHRONO',
        brand: 'ARMANI EXCHANGE',
        collection: 'Street',
        price: 25000,
        image: '/images/generated/armani_exchange_watch.png',
        gender: 'Men',
        category: 'Sports',
        description: 'Bold urban style for the modern professional.'
    },
    {
        id: 'i3',
        name: 'MEGA CHIEF',
        brand: 'DIESEL',
        collection: 'Brave',
        price: 32000,
        image: '/images/generated/diesel_watch.png',
        gender: 'Men',
        category: 'Sports',
        description: 'Aggressive industrial design with multi-timezone support.'
    },
    {
        id: 'i4',
        name: 'SIGNATURE ROSE',
        brand: 'COACH',
        collection: 'Madison',
        price: 28000,
        image: '/images/generated/coach_watch_women.png',
        gender: 'Women',
        category: 'Classic',
        description: 'Elegant rose gold with signature C pattern.'
    },
    {
        id: 'i5',
        name: 'PRX POWERMATIC',
        brand: 'Tissot',
        collection: 'T-Classic',
        price: 65000,
        image: '/images/generated/tissot_prx.png',
        gender: 'Men',
        category: 'Sports',
        description: 'Retro 1970s style with modern automatic precision.'
    },
    {
        id: 'i6',
        name: 'NAVITIMER 1',
        brand: 'Breitling',
        collection: 'Aviator',
        price: 750000,
        image: '/images/generated/breitling_navitimer.png',
        gender: 'Men',
        category: 'Sports',
        description: 'The legendary calculation tool for pilots.'
    },
    {
        id: 'i7',
        name: 'TITAN ADVENTURE',
        brand: 'Garmin',
        collection: 'Fenix',
        price: 85000,
        image: '/images/generated/garmin_fenix_rugged_men_1771156454732.png',
        gender: 'Men',
        category: 'Smart',
        description: 'Built for the ultimate adventure.',
        onSale: true,
        discountPrice: 75000
    },
    {
        id: 's1',
        name: 'APPLE WATCH ULTRA 2',
        brand: 'Apple',
        collection: 'Ultra',
        price: 89900,
        image: '/images/generated/smart_watch_2_1771144637998.png',
        gender: 'Men',
        category: 'Smart',
        description: 'The most rugged and capable Apple Watch.',
        onSale: true,
        discountPrice: 84900
    },
    {
        id: 's2',
        name: 'GALAXY WATCH ULTRA',
        brand: 'Samsung',
        collection: 'Ultra',
        price: 59999,
        image: '/images/generated/smart_watch_3_1771144668331.png',
        gender: 'Men',
        category: 'Smart',
        description: 'For the bold and the brave.',
        onSale: true,
        discountPrice: 54999
    },
    {
        id: 's3',
        name: 'MARQ COMMANDER',
        brand: 'Garmin',
        collection: 'MARQ',
        price: 215000,
        image: '/images/generated/smart_watch_4_1771144686042.png',
        gender: 'Men',
        category: 'Smart',
        description: 'The modern tool watch for tactical operations.',
    },
    {
        id: 's4',
        name: 'TAG HEUER CONNECTED',
        brand: 'Tag Heuer',
        collection: 'Connected',
        price: 245000,
        image: '/images/generated/smart_watch_5_1771144708266.png',
        gender: 'Men',
        category: 'Smart',
        description: 'Swiss watchmaking meets high-tech luxury.',
        onSale: true,
        discountPrice: 220000
    },
    {
        id: 's5',
        name: 'HUAWEI WATCH GT 4',
        brand: 'Huawei',
        collection: 'GT Series',
        price: 19999,
        image: '/images/generated/smart_watch_6_1771144729006.png',
        gender: 'Men',
        category: 'Smart',
        description: 'Fashion Forward, professionally tailored.',
    },
    {
        id: 's6',
        name: 'PIXEL WATCH 3',
        brand: 'Google',
        collection: 'Pixel',
        price: 39999,
        image: '/images/generated/smart_watch_7_1771144747620.png',
        gender: 'Men',
        category: 'Smart',
        description: 'Help by Google. Health by Fitbit.',
    },
    {
        id: 's7',
        name: 'FOSSIL GEN 6',
        brand: 'Fossil',
        collection: 'Gen 6',
        price: 24995,
        image: '/images/generated/smart_watch_8_1771144764232.png',
        gender: 'Men',
        category: 'Smart',
        description: 'Fast charging. Better performance.',
    },
    {
        id: 's8',
        name: 'WITHINGS SCANWATCH',
        brand: 'Withings',
        collection: 'ScanWatch',
        price: 35000,
        image: '/images/generated/smart_watch_9_1771144783908.png',
        gender: 'Men',
        category: 'Smart',
        description: 'The world\'s most advanced health wearable.',
    },
    {
        id: 'i8',
        name: 'MINIMAL FUTURE',
        brand: 'Calvin Klein',
        collection: 'Future',
        price: 18000,
        image: '/images/generated/calvin_klein_minimal.png',
        gender: 'Women',
        category: 'Classic',
        description: 'Pure architectural lines for the contemporary wrist.'
    },
    {
        id: 'sale1',
        name: 'SEIKO 5 SPORTS',
        brand: 'Seiko',
        collection: '5 Sports',
        price: 25000,
        image: '/images/generated/sale_watch_1_1771144844800.png',
        gender: 'Men',
        category: 'Sports',
        description: 'Legendary reliability with a modern twist.',
        onSale: true,
        discountPrice: 19500
    },
    {
        id: 'sale2',
        name: 'TISSOT PR 100',
        brand: 'Tissot',
        collection: 'T-Classic',
        price: 32000,
        image: '/images/generated/sale_watch_2_1771144864193.png',
        gender: 'Women',
        category: 'Classic',
        description: 'A simple, elegant timepiece for every occasion.',
        onSale: true,
        discountPrice: 24000
    },
    {
        id: 'sale3',
        name: 'BULARY OCTO',
        brand: 'Bulgari',
        collection: 'Octo',
        price: 850000,
        image: '/images/generated/bulgari_octo_masculine_dark_final_1771156491859.png',
        gender: 'Men',
        category: 'Luxury',
        description: 'An icon of modern design.',
        onSale: true,
        discountPrice: 790000
    },
    {
        id: 'sale4',
        name: 'CITIZEN ECO-DRIVE',
        brand: 'Citizen',
        collection: 'Eco-Drive',
        price: 18000,
        image: '/images/generated/sale_watch_4_1771144902685.png',
        gender: 'Men',
        category: 'Sports',
        description: 'Powered by any light source.',
        onSale: true,
        discountPrice: 14000
    },
    {
        id: 'sale5',
        name: 'CASIO EDIFICE',
        brand: 'Casio',
        collection: 'Edifice',
        price: 15000,
        image: '/images/generated/sale_watch_5_1771144942924.png',
        gender: 'Men',
        category: 'Sports',
        description: 'Speed and intelligence.',
        onSale: true,
        discountPrice: 12000
    },
    {
        id: 'sale6',
        name: 'TIMEX EXPEDITION',
        brand: 'Timex',
        collection: 'Expedition',
        price: 8500,
        image: '/images/generated/timex_expedition_rugged_men_1771156427923.png',
        gender: 'Men',
        category: 'Sports',
        description: 'The classic outdoor watch.',
        onSale: true,
        discountPrice: 6500
    },
    {
        id: 'sale7',
        name: 'BREITLING AVENGER',
        brand: 'Breitling',
        collection: 'Avenger',
        price: 450000,
        image: '/images/generated/sale_watch_7_1771144988825.png',
        gender: 'Men',
        category: 'Sports',
        description: 'Unmatched performance and bold design.',
        onSale: true,
        discountPrice: 380000
    },
    {
        id: 'sale8',
        name: 'AP ROYAL OAK',
        brand: 'Audemars Piguet',
        collection: 'Royal Oak',
        price: 3500000,
        image: '/images/generated/sale_watch_8_1771145052612.png',
        gender: 'Men',
        category: 'Luxury',
        description: 'The icon of modern luxury watchmaking.',
        onSale: true,
        discountPrice: 2900000
    },
    {
        id: 'sale9',
        name: 'PATEK PHILIPPE SKY MOON',
        brand: 'Patek Philippe',
        collection: 'Grand Complications',
        price: 12000000,
        image: '/images/generated/sale_watch_9_final_1771145127255.png',
        gender: 'Men',
        category: 'Luxury',
        description: 'A masterpiece of celestial watchmaking.',
        onSale: true,
        discountPrice: 11000000
    },

    // --- MORE FILLERS FOR VARIETY ---
    {
        id: 'f1',
        name: 'HAPPY DIAMONDS',
        brand: 'Chopard',
        collection: 'Happy Sport',
        price: 1500000,
        image: '/images/generated/women_watch_2.png',
        gender: 'Women',
        category: 'Luxury',
        description: 'Dancing diamonds for a joyful look.',
    },
    {
        id: 'f2',
        name: 'SERPENTI SEDUTTORI',
        brand: 'Bulgari',
        collection: 'Serpenti',
        price: 2200000,
        image: '/images/generated/women_watch_4.png',
        gender: 'Women',
        category: 'Luxury',
        description: 'Born to be gold, glamorous and seductive.',
    },
    {
        id: 'f3',
        name: 'LIMELIGHT GALA',
        brand: 'Piaget',
        collection: 'Limelight',
        price: 3500000,
        image: '/images/generated/women_watch_cuff.png',
        gender: 'Women',
        category: 'Luxury',
        description: 'Radiant curves and diamonds.',
    },
    {
        id: 'f4',
        name: 'PROSPEX DIVER',
        brand: 'Seiko',
        collection: 'Prospex',
        price: 45000,
        image: '/images/generated/men_watch_1.png',
        gender: 'Men',
        category: 'Sports',
        description: 'High-performance diving technology.',
    }
];
